workflow:
  rules:
    - if: $CI_COMMIT_REF_PROTECTED == "true"
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

default:
  tags:
    - thelab-arm64

stages:
  - test

include:
  - component: gitlab.com/thelabnyc/thelab-ci-components/review@0.8.4
  - component: gitlab.com/thelabnyc/thelab-ci-components/precommit@0.8.4
